---
abstract: 'Parse Tumblr custom themes'
author:
  - 'Benjamin Trott <ben@sixapart.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Tumblr-ThemeParser
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Fast: 0
  HTML::TokeParser: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/btrott/WWW-Tumblr-ThemeParser.git
version: 0.02
